# Site settings
title: Fractal Stack
email: support@fractalstack.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: BatteryAcidDev
github_username: BatteryAcid

# Build settings
markdown: kramdown
